- pkgdb2/api/extras.py
Trying to generate the JSON manually ends up with some invalid JSON as
some packages' summary or description contain some " or some ' which
messes up the JSON we generate.
> Go back to rely on flask.jsonify to generate the JSON output in the API

- tests/test_flask_ui_packages.py
We can patch the whole module and set a return_value for one method in it
but patching the method directly doesn't work.
So we need to create some logs manually to test the timeline endpoint
> Turns out `@patch('pkgdb2.lib.utils.get_packagers')` does not work

- pkgdb2/forms.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- pkgdb2/lib/utils.py
- pkgdb2/templates/actions_update.html
- pkgdb2/templates/list_actions.html
- pkgdb2/templates/request_branch.html
- pkgdb2/ui/packages.py
- tests/test_flask_api_admin.py
- tests/test_flask_ui_packages.py
- tests/test_pkgdblib.py
When requesting a new branch we used to asked from which branch this new branch should be created.
However, the way we automated things, we cannot specify to the script from which branch to create the new one, instead we create the new branch pointing it to the first commit in the repo.
So there is no longer need for us to store this information in the DB nor to display it.
> Drop branch from

- tests/test_flask_api_packages.py
Instead of patching the whole module, we only patch the specific method
we need to patch which thus allowing to check the messages returned by
the API
> Apply the correct patch to be able to check the return messages

- pkgdb2/__init__.py
I specifically want this for the Fedora releng-dash so it can query at
page-load and find out:
- What collections are active and which are EOL.
- What collections are "Under development" but not rawhide.. i.e., are
we currently "branched"?
> Monkey patch flask.jsonify to handle JSONP responses.

- pkgdb2/default_config.py
- utility/pkgdb-sync-bugzilla
Currently admins are getting an email every 10 minutes informing them about invalid mappings. Then, we email the users so that they can act on it.
With this change, users will be automatically notified.
Sometime, it takes a really long time for users to react, recently we have seen more than a week. So while we do not want to spam users as much as we do for admins (every 10 minutes), we still want to pressure them into fixing it by sending them a hourly reminder.
> Warn users about invalid FAS email / bugzilla account mapping

- pkgdb2/templates/acl_update.html
- pkgdb2/templates/list_actions.html
- tests/test_flask_ui_admin.py
This fixes the situation where the user ask for a Fedora branch (ie:
put the status to `Awaiting Review`) while he/she already has the ACL
on for example EPEL branches.
With the current behavior, all branches would be set to `Awaiting Review`
effectively leading to the user loosing the already Approved ACLs.
With this commit `Approved` ACLs are not automatically updated.
Fixes https://fedorahosted.org/pkgdb2/ticket/44
> Do not automatically update branch where the user is Approved

- pkgdb2/templates/package.html
When you click the monitoring toggle and you are not logged in, it makes
the request anyway and then appends "undefined" to the page. This looks
tacky. Instead, if we don't get a response back, just bail out and do
nothing.
Signed-off-by: Ricky Elrod <ricky@elrod.me>
> Fix 'undefined' when clicking monitor toggle.

- utility/update_package_info.py
- F19 is EOL and has been removed from:
http://dl.phx2.fedoraproject.org/pub/fedora/linux/updates/
- F21 has been released and is present at:
http://dl.phx2.fedoraproject.org/pub/fedora/linux/releases/
- F22 is branched and is present at:
http://dl.phx2.fedoraproject.org/pub/fedora/linux/updates/
> Adjust update_package_info for F22, F21 and F19

- utility/pkgdb-sync-bugzilla
When an user gets out of sync between bugzilla and FAS, we get an error
for each package that person maintains (since we cannot sync the ACLs
between pkgdb and bugzilla for each of them).
Before this commit, we would send an email to the user, once per hour,
but also once per error (thus per package that person maintains).
With this commit, we make sure to only send 1 notification per hour and
per user.
> Ensure the user is only notified once

- pkgdb2/templates/master.html
- pkgdb2/ui/__init__.py
For https://fedoraproject.org/wiki/Infrastructure/FY16_frontend
If you leave the fedmenu bits out of the config, it just never shows up.
> Add fedmenu.

- pkgdb2/api/__init__.py
- pkgdb2/api/extras.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- tests/__init__.py
- tests/test_flask_api_extras.py
This adds a new API endpoint listing all the packages retired in every active branch of a specified collection (defaults to: Fedora).
This should fix https://github.com/fedora-infra/pkgdb2/issues/59 for now as there is currently no way to call bugzilla's API to do it automatically.
And fixes https://github.com/fedora-infra/pkgdb2/issues/179
> Retired pkgs

- pkgdb2/templates/list_actions.html
- tests/__init__.py
- tests/test_flask_ui_admin.py
The endpoints is called ``admin_actions`` plural not ``admin_action``
singular.  This was causing a BuildError 500 in production when it tried
to display pagination.
> Fix a typo in the list_actions template.

- pkgdb2/templates/actions_update.html
- pkgdb2/templates/actions_update_ro.html
- pkgdb2/ui/packages.py
- tests/test_flask_ui_packages.py
* Provide a read-only page describing the request
* Rework the package request pages
* Add unit-tests
> Rework the package request pages

- pkgdb2/templates/package_anitya.html
- pkgdb2/ui/packages.py
In those case, we cannot retrieve any JSON information, so we show an
error to the user and do not fail
> Sometime querying anitya fails, we should be able to cope with this

- pkgdb2/templates/package.html
Any packager is allowed to change the koschei status of a package, this is true for the
API but wasn't in the UI. This is now fixed.
Fixes https://github.com/fedora-infra/pkgdb2/issues/215
The link under the ``koschei integration`` button to point to the wiki page instead of the
app directly (the wiki being clearer about what the app does).
> Fix koschei info in the package page

- pkgdb2/api/extras.py
mclasen reported today that he couldn't get pkgdb to auto-populate for
this ticket:  https://bugzilla.redhat.com/show_bug.cgi?id=1229395
That's because "Review Request:" != "Review request:".
This changes the pkgdb code to check the bug component instead, and
tries to be less strict when extracting the name and description.
> Be less strict with bz package review summaries.

- README.rst
The present [url](http://packagedb.readthedocs.org/en/latest/). Probably, what it should be is [this](http://pkgdb2.readthedocs.org/en/latest/)
> Fixed broken link for project documentation

- alembic/versions/80939061434_update_unique_constraints_on_admin_.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- pkgdb2/templates/list_actions.html
- tests/test_flask_ui_admin.py
We cannot make unique an admin action based on its package, branch, user, action and status
otherwise we end up with a request closed, another open that cannot be closed with the same
status (unique constraints will fail).
What we can do otherwise is check if we have a request for that package on that branch and for this user and if so, we reset it.
This PR also adds a link to a request once it has been closed so that it can be sent to someone.
> Adjust how unique an admin action can be

- pkgdb2/templates/package.html
@pypingou @ralphbean added an if-block to check if the user is a package admin or owner or just a random fas user, and accordingly the tooltips as well. Please let me know if this needs further changes :) thankyou.
> Fixed issue #246: Added tooltip for non-admins on clicking monitoring buttons

- pkgdb2/static/pkgdb.css
- pkgdb2/templates/package.html
@pypingou added an "inactive" class in pkgdb.css which enforces default cursor when the fas user is not logged in, while turns into a finger-pointer for a logged in fas user or package admin/owner. Let me know if this still needs work :) Thanks.
> Fixed issue #208: Implemented default cursor for monitoring buttons when user is logged out

- alembic/versions/563dd24698a7_add_the_allow_retire_field_to_the_.py
- pkgdb2/api/collections.py
- pkgdb2/forms.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- pkgdb2/templates/collection.html
- pkgdb2/templates/collection_edit.html
- pkgdb2/templates/collection_new.html
- pkgdb2/ui/collections.py
- tests/__init__.py
- tests/test_collection.py
- tests/test_flask_api_collection.py
- tests/test_flask_api_packagers.py
- tests/test_flask_api_packages.py
- tests/test_package_listing_acl.py
- tests/test_pkgdblib.py
This flag can be used to toggle at any point in time whether someone is allowed to 
retire packages in it.
Fixes https://github.com/fedora-infra/pkgdb2/issues/257
> Add an allow_retire flag to collections

- pkgdb2/templates/package.html
This allows showing the `Un-retire` button instead which is what we want
for retired packages
> Hide the Give button if the package is retired

- pkgdb2/ui/packagers.py
Currently using the side panel, the url looks like:
/packager/pingou/requests?package=&action=&status=Approved
So package and action are both ''.
With this change, they are evaluated and changed to None in those case
actually making filtering requests on the user's page working.
> Fix filtering user's requests using the side panel on the web-page

- pkgdb2/static/koji.css
This way it does not overlap with the options box
Fixes https://github.com/fedora-infra/pkgdb2/issues/276
> Limit the size of the content section

- pkgdb2/api/admin.py
- pkgdb2/forms.py
- pkgdb2/lib/__init__.py
- pkgdb2/templates/actions_update.html
- pkgdb2/templates/actions_update_ro.html
- pkgdb2/templates/request_unretire.html
- pkgdb2/ui/packages.py
- tests/test_pkgdblib.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/277
But this enforce the review_url regardless of the retirement date.
> When un-retiring a package, request the review_url

- pkgdb2/lib/__init__.py
This commit does two fixes:
- It uses the proper key to retrieve the name of the package in the JSON
blob stored in the database to represent an admin action request
- If no package could be found with the provided package name, skip
without failing, this will allow pkgdb-admin to process the whole queue
> Fix processing new package requests

- pkgdb2/ui/acls.py
- tests/test_flask_ui_acls.py
To give ACLs to someone we need the namespace (to figure out which
package we're talking about), but this namespace might not actually be
passed on by the form, in this case, we'll just use the one provided in
the URL.
Adjust the unit-tests to cover this situation
> Fix giving ACLs to someone

- pkgdb2/templates/master.html
When no user is specified for filtering, timeline view displays user-specific fedmenu with broken links.
Reproducer:
- go to https://admin.fedoraproject.org/pkgdb/package/ant/timeline
Actual result:
- user-specific fedmenu is displayed
- user-specific fedmenu contains broken links
Expected result:
- user-specific fedmenu is not displayed
> Fix user-specific fedmenu in package timeline view

- pkgdb2/templates/package.html
Fixes https://fedorahosted.org/pkgdb2/ticket/51
> Encode the package name on the link to koji as it otherwise doesn't work

- pkgdb2/lib/__init__.py
- pkgdb2/lib/notifications.py
Instead of iterating through the element in the DB and doing one query at a time,
we do two queries:
1/ creates the branch for all the packages
2/ sync the ACLs so that the new branch has the same has rawhide.
With this change, doing a branching 
* on my local machine from 1h45 to 25 minutes
* in stg from 5h+ to 32minutes
> Optimize the pkgdb2_branch script used when branching

- pkgdb2/api/acls.py
- pkgdb2/api/admin.py
- pkgdb2/api/collections.py
- pkgdb2/api/packages.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/notifications.py
- pkgdb2/lib/utils.py
- pkgdb2/ui/acls.py
- pkgdb2/ui/admin.py
- pkgdb2/ui/collections.py
- pkgdb2/ui/packagers.py
- pkgdb2/ui/packages.py
- tests/test_pkgdblib.py
This PR first fixes the test suite to not report errors because of undefined exceptions, adds a test for the function to identify the probem, fixes the problem and also fixes some PEP8 violations in the touched files.
This should fix the problem in  https://fedorahosted.org/rel-eng/ticket/6426
> Properly handle bugzilla urls for unretirement requests

- alembic/versions/187e9f9ec178_expand_fas_name_to_255_chars.py
- pkgdb2/lib/model/__init__.py
FAS restrict usernames to 32 characters, so we took the same approach
and restricted our usernames to 32 characters but that was without
thinking about the groups which do not have that restriction on their
names. So far we were lucky but apparently it's time to take it into
account.
> Expand the field fas_name from PackageListingAcl from 32 to 255 chars

- pkgdb2/ui/packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/375
> Ensure the `rpms` namespace is always the first in the list (default)

- .gitignore
- README.rst
- Vagrantfile
- runserver.py
This adds a Vagrant file that allows a developer to quickly
set up a dev environment of pkgdb2 using the infra db dump.
It uses vagrant-libvirt and vagrantsshfs for file syncing.
Also in this change, added a new param in the runserver.py
that allows the host to be set as a commandline param.
> Added Support for dev environment under Vagrant

- pkgdb2/templates/master.html
- pkgdb2/templates/package.html
- pkgdb2/templates/package_anitya.html
- pkgdb2/templates/packager.html
This avoids potential security risk:
https://dev.to/ben/the-targetblank-vulnerability-by-example
https://mathiasbynens.github.io/rel-noopener/
> Specify rel="noopener noreferrer" to link including target='_blank'

- .gitignore
- README.rst
- Vagrantfile
- devel/ansible/playbook.yml
- devel/ansible/roles/core/tasks/main.yml
- devel/ansible/roles/db/tasks/main.yml
- devel/ansible/roles/dev/tasks/main.yml
This changes the was we provision the vagrant devel
envrionment, from the shell provisioner to the ansible
one.
These changes are based heavily on the same work done by @bowlofeggs on bodhi in https://github.com/fedora-infra/bodhi/pull/893
> Change vagrant provisioning to use ansible

- devel/ansible/roles/dev/tasks/main.yml
Previously, the vagrant config did not upgrade the database
when provisioning the new machine. This could lead to issues
if a database change was commited to master, and we pull the
dbdump from prod.
This change copies the alembic.ini from the utility directory,
changes the dburl to what the vagrant setup expects, and runs
the alembic upgrade command.
> update vagrant ansible role to upgrade database

- README.rst
Previously the vagrant-sshfs plugin was only available for fedora via COPR. now it is in the main Fedora repos, the README is updated to insctruct new users to get it from there.
> Update the README fixing the vagrant-sshfs parts

- pkgdb2/api/extras.py
tmp was just the :, due to the partition(':')[1].
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Fix bug title splitting

- pkgdb2/lib/__init__.py
When we approve a new package request, in any namespace, we normally go
then through all the other pending requests to automatically create the
branch (for the branches for which we can).
With non-rpm namespaces, this logic was broken since we were not including
the namespace in the search for other requests and we were ending up
with an exception saying that there are no such package.
This was confusing when processing the requests via pkgdb-admin since it
would return an error (not even a clear one) and then when checking the
UI, the new package was created.
This commit fixes that situation.
> Fix approving a new package request in the docker namespace

- pkgdb2/lib/__init__.py
Turns out we need a `status` variable to send the fedmsg notif about
status change, so let's have one so that our code compiles and actually
works.
> Fix bug: missing variable `status` -- thanks unit-tests

- doc/groups.rst
BTW, if there was a way to open pagure ticket with prefilled subject and body, that would be sweet ...
> Update documentation to refer to pagure.io instead of trac

- doc/groups.rst
This is attempt to provide more insight how to setup the package ACL when it should be maintained by FAS group.
> Document suggested setup of package maintained by group.

- pkgdb2/lib/model/__init__.py
The identifier must be part of the group_by on postgresql otherwise
it fails.
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>
> Fix running the query on postgresql
