- pkgdb2/lib/model/__init__.py
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Add missing join condition

- pkgdb2/templates/package.html
Should help a little more with https://github.com/fedora-infra/pkgdb2/issues/119
> Add a title to the 'Retired' status to indicate it's clickable

- pkgdb2/static/pkgdb.css
- pkgdb2/ui/__init__.py
This makes it so that when you are logged in, anywhere your avatar
appears it will be clickable and will take you to libravatar so you can
change it.  Importantly, you'll be logged into libravatar correctly
which can sometimes be tricky.
> Make it easy to change your avatar.

- utility/set_monitoring_status.py
Staging has a proper certificate, no need to not check it
> Do not use insecure pkgdb

- pkgdb2/lib/__init__.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/165
> Improve readability of pkgdb.lib.vcs_acls by using proper variable names

- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- tests/test_package.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/177
> Turn off monitoring when the package is retired on all branches.

- pkgdb2/templates/package_anitya.html
- pkgdb2/ui/packages.py
Fix https://github.com/fedora-infra/pkgdb2/issues/194
> Offer the possibility to map the package in anitya

- pkgdb2/__init__.py
- pkgdb2/ui/__init__.py
fixes https://github.com/fedora-infra/pkgdb2/issues/193
> Improve the logout behavior

- pkgdb2/templates/packager.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/199
> Retrieve the user's status from fedocal is configured to do so

- pkgdb2/templates/package.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/218
> Let packager toggle in the UI the koschei status for all packages

- fedmsg.d/pkgdb.py
See: https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=d50c77ec
> PackageDB in Fedora infra uses dynamic fedmsg endpoints now

- pkgdb2/api/extras.py
- pkgdb2/forms.py
- pkgdb2/templates/package_request.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/229
> Improve the package request page to support giving only a ticket id

- pkgdb2/templates/package_request.html
- pkgdb2/ui/packages.py
- Make the fields readonly instead of disabling them (disable them mean they are not submitted so the form doesn't work :/)
- Ensure the review URL is a full URL not just the ticket identifier
> Couple of bug fixes

- pkgdb2/lib/__init__.py
- tests/test_flask_ui_acls.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/217
> Prevent the PoC of a package to be removed of his/her watch* ACLs

- pkgdb2/templates/package.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/210
> Add a button to request approveacls per branch

- pkgdb2/lib/__init__.py
Fixes https://fedorahosted.org/pkgdb2/ticket/47
> Give ACLs to the new POC of a package

- runserver.py
Do the import after setting the environment variable, otherwise that
won't work
> Fix the runserver script

- pkgdb2/templates/list_actions.html
- tests/test_flask_ui_admin.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/252
> Fix pagination in the `My requests` page and the unit-tests

- pkgdb2/api/__init__.py
- pkgdb2/api/packages.py
- tests/test_flask_api_packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/239
> Add a new API endpoint to request pkg

- pkgdb2/templates/acl_update.html
Fixes https://fedorahosted.org/pkgdb2/ticket/46
> Only automatically update 'Awaiting Review' ACL requests

- pkgdb2/api/collections.py
- tests/test_flask_api_collection.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/260
> Fix listing collections in the API

- alembic/versions/33d905fb1f55_date_updated_for_collections.py
- pkgdb2/api/collections.py
- pkgdb2/lib/model/__init__.py
- pkgdb2/templates/collection.html
- tests/test_collection.py
- tests/test_flask_api_collection.py
- tests/test_flask_api_packagers.py
- tests/test_package_listing_acl.py
Fixes https://fedorahosted.org/pkgdb2/ticket/49
> Register and show the date of the last update of a collection

- pkgdb2/templates/package.html
- pkgdb2/ui/acls.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/209
> Ignore the retired branch when requesting commit or watch* ACLs

- pkgdb2/forms.py
- pkgdb2/lib/__init__.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/272
> Strip the input (if there is one) when a new package is requested

- pkgdb2/api/extras.py
With these changes we check that the review was assigned to someone and
that the fedora-review flag was set to `+`.
Fixes https://github.com/fedora-infra/pkgdb2/issues/269
> Improve the checks to the package review on bugzilla before letting it through

- pkgdb2/lib/__init__.py
- pkgdb2/ui/packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/286
> Let the user update request to unretire to `Awaiting Review`

- pkgdb2/ui/packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/287
> Restrict the branches proposed to un-retire to the last two Fedora releases

- pkgdb2/api/extras.py
Fixes https://github.com/fedora-infra/packagedb-cli/issues/62
> Perform more checks around the fedora-review flag when syncing info from bugzilla

- pkgdb2/templates/actions_update.html
I am not able to see the issue since I was unable to make myself admin in my local instance, let me know if this fixes #278 
Thanks :)
> Making sure that the request states are not accidentally changed when user is admin

- pkgdb2/lib/__init__.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/285
> When approving a new package, process the new Fedora branch requests as well

- pkgdb2/templates/list_packages.html
- runserver.py
- Add the namespace to the link as everywhere else
- Allow filtering the packages for a given namespace
- Fix the runserver script (unrelated to the other changes but still needed)
> Fix the page listing all the packages

- pkgdb2/lib/__init__.py
- tests/test_pkgdblib.py
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Fix wrongly named variable

- pkgdb2/ui/packages.py
- tests/__init__.py
- tests/test_flask_ui_admin.py
- tests/test_flask_ui_packages.py
Adjust unit-tests to cover this situation
> Handle the situation where there is no package linked to the request

- pkgdb2/templates/package.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/309
> Avoid touching the monitoring button when toggling koshei integration

- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- pkgdb2/ui/admin.py
- pkgdb2/ui/packagers.py
fixes https://fedorahosted.org/pkgdb2/ticket/53
> Show admin requests in the UI, most recents first

- pkgdb2/api/packages.py
- tests/test_flask_api_packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/317
> Expand /api/packages to search multiple patterns at once

- pkgdb2/api/extras.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/319
> Include namespace in api_dead_package

- pkgdb2/forms.py
- pkgdb2/lib/__init__.py
- pkgdb2/templates/package_request.html
- pkgdb2/ui/packages.py
Fixes https://fedorahosted.org/pkgdb2/ticket/54
> Allow specifying co-maintainers when requesting a new package to be added

- pkgdb2/api/packages.py
- pkgdb2/default_config.py
- pkgdb2/lib/__init__.py
- pkgdb2/ui/packages.py
- tests/__init__.py
- tests/test_flask_api_extras.py
- tests/test_flask_api_packages.py
- tests/test_package.py
- tests/test_package_listing.py
- tests/test_package_listing_acl.py
- tests/test_pkgdblib.py
- utility/pkgdb2_branch.py
Fixes #341.
I think this is correct.  Did I miss any other API endpoints that need this?
> Enforce a namespace policy.

- pkgdb2/api/packages.py
- tests/test_flask_api_packages.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/334
> Fix permission check on who can un-retire a package

- pkgdb2/templates/list_actions.html
Fixes https://github.com/fedora-infra/pkgdb2/issues/346
> Fix the pagination when browsing the requests to include the status info

- pkgdb2/lib/__init__.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/142
> Keep the status change of the packae/branch info when doing mass branching

- utility/pkgdb2_branch.py
With some user interaction it can now update the rawhide collection
and then create the new branch before doing the branching.
Meaning there is no longer any need to use the web-ui, then go CLI
to do the branching.
> Improve the mass-branching script

- pkgdb2/lib/__init__.py
- tests/test_pkgdblib.py
Added a test for it as well.
Fixes #352.
> Check namespace policy on branch request.

- pkgdb2/__init__.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/utils.py
- pkgdb2/templates/package.html
- pkgdb2/ui/__init__.py
- pkgdb2/ui/acls.py
- pkgdb2/ui/packages.py
Instead, allow them to be set in the configuration file
> Do not hard-code packager and provenpackager in the code

- pkgdb2/ui/packages.py
- pkgdb2/ui/redirects.py
- tests/test_flask.py
- tests/test_flask_ui_acls.py
- tests/test_flask_ui_packages.py
Since we are able to filter by namespace, this will let Package return everything,
regardless of the namespaces.
> Let the Package return everything regardless of the namespace

- pkgdb2/mail_logging.py
Fixes https://github.com/fedora-infra/pkgdb2/issues/369
> When sending error report, use PKGDB2_EMAIL_FROM from the configuration

- pkgdb2/default_config.py
- pkgdb2/templates/package.html
fixes https://github.com/fedora-infra/pkgdb2/issues/370
> Add support for the namespace in the cgit URL

- pkgdb2/default_config.py
- pkgdb2/forms.py
- tests/test_flask_api_packages.py
- utility/pkgdb2.cfg.sample
Fixes: #374
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Implement blacklisting feature

- pkgdb2/api/extras.py
- pkgdb2/lib/__init__.py
- pkgdb2/lib/model/__init__.py
- tests/__init__.py
- tests/test_flask_api_extras.py
- utility/pkgdb-sync-bugzilla
Now that pkgdb has the concept of namespace this needs to be propagated to BZ.
This PR should allow it.
> Adjust the bugzilla API endpoint to sync ACLs to bugzilla for more products

- utility/pkgdb-sync-bugzilla
Otherwise we run into KeyError exceptions for rather logical reasons
> Fix the location where the collection is converted into a product

- pkgdb2/lib/__init__.py
Turns out we were doing pretty bad at announcing when we changed the
status of a package on a certain branch (ie: going from Approved to
Orphaned or Retired and the other way around).
This commit fixes this.
Fixes https://github.com/fedora-infra/pkgdb2/issues/378
> Fix sending notifications when we update the status of a package on a branch
